# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Artifacts and Release

on:
  push:
    paths:
      - AoC.Games/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Publish macOS Intel
      run: dotnet publish ./AoC.Games/AoC.Games.csproj -c Release -r osx-x64 /p:PublishReadyToRun=true /p:TieredCompilation=false --self-contained
    - name: Publish macOS Apple
      run: dotnet publish ./AoC.Games/AoC.Games.csproj -c Release -r osx-arm64 /p:PublishReadyToRun=true /p:TieredCompilation=false --self-contained
    - name: Publish Windows Intel
      run: dotnet publish ./AoC.Games/AoC.Games.csproj -c Release -r win-x64 /p:PublishReadyToRun=true /p:TieredCompilation=false --self-contained
    - name: Zip macOS Intel Package
      run: zip -r AoC.Games.macOS.Intel.zip AoC.Games/bin/Release/net8.0/osx-x64/publish
    - name: Zip macOS Apple Package
      run: zip -r AoC.Games.macOS.Apple.zip AoC.Games/bin/Release/net8.0/osx-arm64/publish
    - name: Zip Windows Intel Package
      run: zip -r AoC.Games.Windows.zip AoC.Games/bin/Release/net8.0/win-x64/publish
